pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
                sh 'ls *'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t jenkinsflaskapp:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        //stage('Push Image') {
        //    steps {
        //        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
        //        }
        //    }
        //}
    }
}
