pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('dockerhub')
    }
    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
                sh 'ls *'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t raj80dockerid/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Docker Login') {
            steps {
                //sh 'echo $DOCKERHUB_CREDES_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
                }
            }
        stage('Docker Push') {
            steps {
                sh 'docker push raj80dockerid/jenkinstest:$BUILD_NUMBER'
                }
            }
        }
    }

