pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                  //  image 'node:latest'
                }
            }
            steps {
                sh 'python -m py_compile pythoncode/add2vals.py pythoncode/calc.py'
                sh 'dockre'
                stash(name: 'compiled-results', includes: 'pythoncode/*.py*')
                sh 'pwd'
                sh 'echo "using ls /"'
                sh 'ls /'
                sh 'echo "using ls /"'
                sh 'ls -l pythoncode'
                sh 'whoami'
            }
        }
        stage('Test') { 
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --junit-xml test-reports/results.xml pythoncode/test_calc.py' 
                sh 'cat test-reports/results.xml'
                sh 'pwd'
                sh 'ls -lrt'
            }
            post {
                always {
                    junit 'test-reports/results.xml' 
                    sh 'pwd'
                    sh 'ls -lrt'
                }
            }
        }
    }
}
